-- P's Trip 시드 데이터: 서울 장소 15개 (FOOD 5, ATTRACTION 5, SHOPPING 5)
-- 기존 목데이터 6개 포함 + 신규 9개 추가

insert into places (name_en, name_ko, category, city, description, description_long, images, latitude, longitude, address_en, address_ko, operating_hours, closed_days, nearest_station, walk_minutes, budget_min, budget_max, dokkaebi_tip, google_maps_url, tags, rating, weight, source) values

-- === FOOD ===
(
  'Gwangjang Market',
  '광장시장',
  'FOOD', 'SEOUL',
  'One of Seoul''s oldest and largest traditional markets, famous for bindaetteok, mayak gimbap, and knife-cut noodles.',
  'One of Seoul''s oldest and largest traditional markets, dating back to 1905. Famous for bindaetteok (mung bean pancakes), mayak gimbap (addictive mini rice rolls), and fresh knife-cut noodles. Come hungry — this is where locals eat. The night market section is especially lively on weekends.',
  '{}',
  37.5700, 126.9990,
  '88 Changgyeonggung-ro, Jongno-gu, Seoul',
  '서울 종로구 창경궁로 88',
  '9:00 AM - 11:00 PM',
  'Sundays',
  'Jongno 5-ga (Line 1)',
  2, 5000, 15000,
  'Try the mayak gimbap first — you''ll see why they call it addictive. Pro tip: the stalls in the back alleys are where locals go.',
  'https://maps.google.com/?q=Gwangjang+Market+Seoul',
  '{"street-food","traditional","budget","market"}',
  4.5, 1.00, 'MANUAL'
),
(
  'Tosokchon Samgyetang',
  '토속촌삼계탕',
  'FOOD', 'SEOUL',
  'Iconic restaurant near Gyeongbokgung, famous for ginseng chicken soup served in a bubbling stone pot.',
  'A Seoul institution near Gyeongbokgung Palace, Tosokchon has been serving its legendary samgyetang (ginseng chicken soup) since 1983. The whole young chicken is stuffed with glutinous rice, jujubes, and ginseng, then slow-cooked until fall-off-the-bone tender. Expect a queue during lunch — it''s worth the wait.',
  '{}',
  37.5759, 126.9717,
  '5 Jahamun-ro 5-gil, Jongno-gu, Seoul',
  '서울 종로구 자하문로5길 5',
  '10:00 AM - 10:00 PM',
  null,
  'Gyeongbokgung (Line 3)',
  5, 16000, 22000,
  'Go right when they open at 10 AM to skip the line. Add the extra ginseng liquor on the side — trust the Dokkaebi on this one.',
  'https://maps.google.com/?q=Tosokchon+Samgyetang+Seoul',
  '{"korean-food","traditional","must-try","historic"}',
  4.3, 1.00, 'MANUAL'
),
(
  'Maple Tree House',
  '단풍나무집',
  'FOOD', 'SEOUL',
  'A premium Korean BBQ restaurant in Itaewon loved by locals and tourists alike for its high-quality hanwoo beef.',
  'Located in the heart of Itaewon, Maple Tree House serves some of the best Korean BBQ in Seoul. Their marinated galbi and fresh samgyeopsal are grilled to perfection at your table. The cozy wooden interior and attentive service make it a standout among Seoul''s many BBQ joints.',
  '{}',
  37.5345, 126.9946,
  '7 Itaewon-ro 26-gil, Yongsan-gu, Seoul',
  '서울 용산구 이태원로26길 7',
  '11:30 AM - 10:00 PM',
  null,
  'Itaewon (Line 6)',
  3, 25000, 50000,
  'Order the marinated galbi set — it comes with all the banchan you need. Lunch is cheaper than dinner for the same quality meat.',
  'https://maps.google.com/?q=Maple+Tree+House+Itaewon+Seoul',
  '{"korean-bbq","premium","must-try","itaewon"}',
  4.4, 1.00, 'MANUAL'
),
(
  'Tongin Market Lunch Box Café',
  '통인시장 도시락카페',
  'FOOD', 'SEOUL',
  'A unique traditional market where you buy brass coins and fill your own lunch box from different vendor stalls.',
  'Tongin Market near Gyeongbokgung offers a one-of-a-kind experience: buy a set of yeopjeon (old Korean brass coins) at the café, then walk around the market filling your lunch box with dishes from different stalls. Each item costs 1-2 coins. It''s the most fun way to try a variety of Korean street food in one sitting.',
  '{}',
  37.5796, 126.9690,
  '18 Jahamun-ro 15-gil, Jongno-gu, Seoul',
  '서울 종로구 자하문로15길 18',
  '11:00 AM - 5:00 PM',
  'Mondays',
  'Gyeongbokgung (Line 3)',
  8, 5000, 10000,
  'Get the coin set (5,000 KRW) and go straight to the japchae and tteokbokki stalls first — they sell out fast. Best combined with a Gyeongbokgung visit.',
  'https://maps.google.com/?q=Tongin+Market+Seoul',
  '{"street-food","unique","budget","traditional"}',
  4.2, 1.00, 'MANUAL'
),
(
  'Noryangjin Fish Market',
  '노량진수산시장',
  'FOOD', 'SEOUL',
  'Seoul''s massive wholesale fish market where you pick live seafood and have it prepared on the spot.',
  'The largest fish market in Seoul, Noryangjin is a sensory overload of tanks with live fish, octopus, crab, and shellfish. Pick what you want from the vendors on the first floor, negotiate a price, then take it upstairs to a restaurant that will prepare it as sashimi, grilled, or in a stew — for a small fee.',
  '{}',
  37.5133, 126.9408,
  '674 Nodeul-ro, Dongjak-gu, Seoul',
  '서울 동작구 노들로 674',
  '24 hours (market), restaurants vary',
  null,
  'Noryangjin (Line 1/9)',
  1, 20000, 60000,
  'Go early morning (6-7 AM) for the freshest picks and best prices. Don''t be shy to negotiate — vendors expect it. The spicy seafood stew (매운탕) from your leftover fish bones is free!',
  'https://maps.google.com/?q=Noryangjin+Fish+Market+Seoul',
  '{"seafood","market","fresh","experience"}',
  4.3, 1.00, 'MANUAL'
),

-- === ATTRACTION ===
(
  'Bukchon Hanok Village',
  '북촌한옥마을',
  'ATTRACTION', 'SEOUL',
  'A charming neighborhood of traditional Korean hanok houses between Gyeongbokgung and Changdeokgung palaces.',
  'Nestled between two grand palaces, Bukchon is a living neighborhood of over 900 traditional Korean hanok houses. Wander the narrow alleys of Gahoe-dong for the most iconic views. Best visited early morning before the crowds arrive. The rooftop cafes overlooking the tiled roofs are a hidden gem.',
  '{}',
  37.5826, 126.9831,
  '37 Gyedong-gil, Jongno-gu, Seoul',
  '서울 종로구 계동길 37',
  'Open 24 hours (outdoor area)',
  null,
  'Anguk (Line 3)',
  3, null, null,
  'Skip the main street — turn into the tiny alleys near Gahoe-dong 31. That''s where the real magic is. And keep it quiet, people live here!',
  'https://maps.google.com/?q=Bukchon+Hanok+Village+Seoul',
  '{"historic","photo-spot","culture","free"}',
  4.4, 1.00, 'MANUAL'
),
(
  'Namsan Seoul Tower',
  '남산서울타워',
  'ATTRACTION', 'SEOUL',
  'Seoul''s iconic landmark tower on Namsan Mountain, offering panoramic city views and the famous love lock fence.',
  'Standing at 236 meters atop Namsan Mountain, N Seoul Tower is the city''s most recognizable landmark. Take the cable car or hike the scenic trail through the forest. The observation deck offers 360-degree views of the entire Seoul skyline. The love lock fence at the base is a must-see for couples.',
  '{}',
  37.5512, 126.9882,
  '105 Namsangongwon-gil, Yongsan-gu, Seoul',
  '서울 용산구 남산공원길 105',
  '10:00 AM - 11:00 PM',
  null,
  'Myeongdong (Line 4)',
  15, 16000, 16000,
  'Take the hiking trail from Myeongdong instead of the cable car — it''s only 30 minutes and way more scenic. Go at sunset for the best views.',
  'https://maps.google.com/?q=N+Seoul+Tower',
  '{"landmark","views","romantic","instagram"}',
  4.2, 1.00, 'MANUAL'
),
(
  'Changdeokgung Palace',
  '창덕궁',
  'ATTRACTION', 'SEOUL',
  'A UNESCO World Heritage palace with the stunning Secret Garden, considered the most beautiful of Seoul''s five palaces.',
  'Built in 1405, Changdeokgung is the best-preserved of Seoul''s five grand palaces. The highlight is Huwon (Secret Garden), a meticulously landscaped garden with pavilions, ponds, and centuries-old trees. The garden tour is limited to small groups, creating an intimate experience.',
  '{}',
  37.5794, 126.9910,
  '99 Yulgok-ro, Jongno-gu, Seoul',
  '서울 종로구 율곡로 99',
  '9:00 AM - 6:00 PM',
  'Mondays',
  'Anguk (Line 3)',
  5, 3000, 8000,
  'Book the Secret Garden tour in advance — it sells out! The last tour of the day is the most peaceful. Wear comfortable shoes, the garden paths are uneven.',
  'https://maps.google.com/?q=Changdeokgung+Palace+Seoul',
  '{"palace","UNESCO","garden","historic"}',
  4.6, 1.00, 'MANUAL'
),
(
  'Ikseon-dong Hanok Alley',
  '익선동 한옥골목',
  'ATTRACTION', 'SEOUL',
  'A trendy hanok alley transformed into a hip neighborhood with cafes, vintage shops, and photo-worthy corners.',
  'Ikseon-dong is Seoul''s coolest hanok neighborhood — century-old traditional houses converted into Instagram-worthy cafes, restaurants, and boutiques. Unlike touristy Bukchon, Ikseon-dong has a local, artsy vibe. The narrow alleys are perfect for wandering without a plan.',
  '{}',
  37.5724, 126.9920,
  'Ikseon-dong, Jongno-gu, Seoul',
  '서울 종로구 익선동',
  '10:00 AM - 10:00 PM (varies by shop)',
  null,
  'Jongno 3-ga (Line 1/3/5)',
  3, null, null,
  'Come on a weekday to avoid the crowds. The tiny alley behind the main strip has the best hidden cafes. Try the souffle pancake at the corner shop — thank me later.',
  'https://maps.google.com/?q=Ikseon-dong+Seoul',
  '{"trendy","cafe","photo-spot","hanok"}',
  4.3, 1.00, 'MANUAL'
),
(
  'Seoullo 7017 Skygarden',
  '서울로 7017',
  'ATTRACTION', 'SEOUL',
  'A former highway overpass transformed into an elevated garden walkway with city views, near Seoul Station.',
  'Inspired by New York''s High Line, Seoullo 7017 is a 983-meter elevated park built on a 1970 highway overpass. Walk among 24,000 plants representing 228 species while enjoying panoramic views of Seoul Station area. The walkway connects Namdaemun Market, Namsan, and Seoul Station.',
  '{}',
  37.5559, 126.9723,
  '405 Hangang-daero, Jung-gu, Seoul',
  '서울 중구 한강대로 405',
  'Open 24 hours',
  null,
  'Seoul Station (Line 1/4)',
  1, null, null,
  'Visit at night when the LED lights turn on — completely different vibe. Start from Seoul Station end and walk toward Namdaemun Market for the best flow.',
  'https://maps.google.com/?q=Seoullo+7017+Seoul',
  '{"park","free","views","architecture"}',
  4.0, 1.00, 'MANUAL'
),

-- === SHOPPING ===
(
  'Hongdae Free Market',
  '홍대 프리마켓',
  'SHOPPING', 'SEOUL',
  'A vibrant weekend flea market in Hongdae where young artists sell handmade goods, art, and unique finds.',
  'Every Saturday in Hongdae''s playground park, local artists and designers set up stalls selling handmade jewelry, illustrations, pottery, and one-of-a-kind accessories. It''s the perfect place to find unique souvenirs you won''t see anywhere else. The surrounding streets are filled with buskers, street performers, and indie shops.',
  '{}',
  37.5563, 126.9236,
  'Wausan-ro 21-gil, Mapo-gu, Seoul',
  '서울 마포구 와우산로21길',
  '1:00 PM - 6:00 PM (Saturdays only)',
  'Sunday - Friday',
  'Hongik University (Line 2)',
  5, 5000, 30000,
  'The best stuff sells out by 3 PM. Get there early and bring cash — most artists don''t take cards. Check the alleys behind the park for hidden vintage shops.',
  'https://maps.google.com/?q=Hongdae+Free+Market+Seoul',
  '{"handmade","art","unique","weekend-only"}',
  4.1, 1.00, 'MANUAL'
),
(
  'Myeongdong Shopping Street',
  '명동쇼핑거리',
  'SHOPPING', 'SEOUL',
  'Seoul''s busiest shopping district with K-beauty stores, fashion brands, and amazing street food stalls.',
  'Myeongdong is Seoul''s retail heart — a neon-lit paradise packed with K-beauty flagship stores, Korean fashion brands, and international labels. The real stars are the street food stalls lining every corner: try the tornado potato, egg bread, and hotteok. Most stores offer tax-free shopping for tourists.',
  '{}',
  37.5636, 126.9827,
  'Myeongdong-gil, Jung-gu, Seoul',
  '서울 중구 명동길',
  '10:30 AM - 10:00 PM',
  null,
  'Myeongdong (Line 4)',
  1, 10000, 100000,
  'Don''t buy K-beauty at the first store you see — prices vary wildly. And the street food is best after 5 PM when all the stalls are open. Ask for tax refund!',
  'https://maps.google.com/?q=Myeongdong+Shopping+Street+Seoul',
  '{"k-beauty","fashion","street-food","tax-free"}',
  4.0, 1.00, 'MANUAL'
),
(
  'Gangnam Underground Shopping Center',
  '강남역 지하상가',
  'SHOPPING', 'SEOUL',
  'A massive underground shopping mall beneath Gangnam Station with affordable Korean fashion and accessories.',
  'Stretching beneath Gangnam Station, this underground maze of shops offers trendy Korean fashion at bargain prices. From clothing and accessories to cosmetics and phone cases, it''s a one-stop shop for affordable style. Great for rainy days or summer heat escape.',
  '{}',
  37.4979, 127.0276,
  'Gangnam-daero, Seocho-gu, Seoul',
  '서울 서초구 강남대로 지하',
  '10:00 AM - 10:00 PM',
  null,
  'Gangnam (Line 2)',
  0, 5000, 50000,
  'The shops near exit 10 have the best Korean fashion deals. Bargaining is expected at the smaller stalls. Check the shoe section near the middle — hidden gems everywhere.',
  'https://maps.google.com/?q=Gangnam+Underground+Shopping+Seoul',
  '{"fashion","budget","underground","gangnam"}',
  3.9, 1.00, 'MANUAL'
),
(
  'Garosu-gil',
  '가로수길',
  'SHOPPING', 'SEOUL',
  'A tree-lined street in Sinsa-dong famous for boutique shopping, designer cafes, and a fashionable atmosphere.',
  'Garosu-gil (Tree-lined Street) in Sinsa-dong is Seoul''s most stylish shopping strip. The ginkgo tree-lined main road features Korean designer boutiques, concept stores, and upscale cafes. Dive into the side alleys (serosu-gil) for indie shops, art galleries, and hidden brunch spots.',
  '{}',
  37.5200, 127.0230,
  'Garosu-gil, Gangnam-gu, Seoul',
  '서울 강남구 가로수길',
  '11:00 AM - 9:00 PM (varies by shop)',
  null,
  'Sinsa (Line 3)',
  5, 10000, 80000,
  'Skip the main street''s big brands — the real finds are in serosu-gil (the side alleys). The vintage shops near the south end are chef''s kiss.',
  'https://maps.google.com/?q=Garosu-gil+Sinsa+Seoul',
  '{"boutique","designer","trendy","cafe"}',
  4.1, 1.00, 'MANUAL'
),
(
  'Namdaemun Market',
  '남대문시장',
  'SHOPPING', 'SEOUL',
  'Korea''s largest traditional market, open since 1414, offering everything from food to clothes to souvenirs at wholesale prices.',
  'Namdaemun is Korea''s oldest and largest traditional market, with over 10,000 shops. You can find literally anything here — from handmade accessories and traditional crafts to imported goods and bulk snacks. The food alleys serve some of the best kalguksu (knife-cut noodles) and hotteok in Seoul.',
  '{}',
  37.5592, 126.9775,
  '21 Namdaemunsijang 4-gil, Jung-gu, Seoul',
  '서울 중구 남대문시장4길 21',
  '24 hours (some sections close at night)',
  'Sundays (some sections)',
  'Hoehyeon (Line 4)',
  2, 3000, 50000,
  'The wholesale section opens at midnight for the real deals. For daytime visits, the children''s clothing section and accessories alley have the best bargains. Don''t miss the famous kalguksu alley!',
  'https://maps.google.com/?q=Namdaemun+Market+Seoul',
  '{"traditional","wholesale","budget","souvenirs"}',
  4.2, 1.00, 'MANUAL'
);
